
# Loads default set of integrations. Do not remove.
default_config:

  
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml



# https://www.home-assistant.io/integrations/modbus
# https://watts247.com/manuals/gw/GrowattModBusProtocol.pdf
modbus:
  - name: "sacolar inverter"
    close_comm_on_error: true
    delay: 5
    timeout: 5

    type: serial
    baudrate: 9600
    bytesize: 8
    method: rtu
    parity: E
    port: /dev/ttyUSB-SERIAL
    stopbits: 1

    sensors:
      - name: 17 Inverter Status
        slave: 1
        scan_interval: 2
        address: 0
        input_type: input

      - name: 16 PV1 Voltage
        unit_of_measurement: V
        device_class: current
        slave: 1
        scan_interval: 2
        address: 1
        input_type: input
        scale: 0.1

      - name: 11 PV1 Power
        unit_of_measurement: W
        device_class: power
        slave: 1
        scan_interval: 2
        address: 3
        input_type: input
        data_type: int32
        scale: 0.1

      - name: 13 Bat Charge Current
        unit_of_measurement: A
        slave: 1
        scan_interval: 2
        address: 7
        input_type: input
        scale: 0.1

      - name: 24 AC Charge Watt
        unit_of_measurement: W
        device_class: power
        slave: 1
        scan_interval: 2
        address: 13
        input_type: input
        data_type: int32
        scale: 0.1
        
      - name: 25 Battery Voltage
        unit_of_measurement: V
        device_class: current
        slave: 1
        scan_interval: 2
        address: 17
        input_type: input
        scale: 0.01

      - name: 14 Battery SOC
        unit_of_measurement: "%"
        slave: 1
        scan_interval: 2
        address: 18
        input_type: input

      - name: 15 Load Percent
        unit_of_measurement: "%"
        slave: 1
        scan_interval: 2
        address: 27
        input_type: input
        scale: 0.1

      - name: 20 Inverter Output Current
        unit_of_measurement: A
        slave: 1
        scan_interval: 2
        address: 34
        input_type: input
        scale: 0.1

      - name: 10 AC Input Watt
        unit_of_measurement: W
        device_class: power
        slave: 1
        scan_interval: 2
        address: 36
        input_type: input
        data_type: int32
        scale: 0.1

      - name: 19 PV Energy Today
        unit_of_measurement: kWh
        slave: 1
        scan_interval: 2
        address: 49
        input_type: input
        scale: 0.1

      - name: 22 AC Charge Energy Today
        unit_of_measurement: kWh
        slave: 1
        scan_interval: 2
        address: 56
        input_type: input
        data_type: int32
        scale: 0.1

      - name: 23 Battery Discharge Energy Today
        unit_of_measurement: kWh
        slave: 1
        scan_interval: 2
        address: 60
        input_type: input
        data_type: int32
        scale: 0.1

      - name: Inverter AC Charge Battery Current
        unit_of_measurement: A
        slave: 1
        scan_interval: 2
        address: 68
        input_type: input
        scale: 0.1

      - name: 30 AC Output Config 
        unit_of_measurement: "[0: Batt First; 1: PV First; 2: UTI First; 3:PV&UTI First]"
        slave: 1
        scan_interval: 2
        address: 1
        input_type: holding

      - name: 31 AC Charge Source
        unit_of_measurement: "[0: PV First; 1: PV&UTI; 2: PV Only]"
        slave: 1
        scan_interval: 2
        address: 2
        input_type: holding
        
      - name: 32 Overload Restart
        unit_of_measurement: "[0: Yes; 1: No; 2: Switch to UTI]"
        slave: 1
        scan_interval: 2
        address: 20
        input_type: holding

      - name: 33 Max Charge Current
        unit_of_measurement: A
        slave: 1
        scan_interval: 2
        address: 34
        input_type: holding

      - name: 34 Inverter Time Hour
        unit_of_measurement: h
        slave: 1
        scan_interval: 2
        address: 48
        input_type: holding
        
      - name: 35 Inverter Time Minute
        unit_of_measurement: m
        slave: 1
        scan_interval: 2
        address: 49
        input_type: holding
        
